# EC2
resource "aws_instance" "db" {
  ami                    = var.ami_id
  instance_type          = var.instance_type
  subnet_id              = var.subnet_id
  vpc_security_group_ids = [var.sg_postgres_id]
  key_name               = var.key_name
  associate_public_ip_address = false

  root_block_device {
    volume_size = var.volume_size
    volume_type = var.volume_type
    iops        = var.volume_iops
  }

  user_data = <<-EOF
    #!/bin/bash
    sudo apt update
    sudo apt install postgresql postgresql-contrib -y
    sudo systemctl start postgresql
    sudo systemctl enable postgresql
    PG_CONF="/etc/postgresql/16/main/postgresql.conf"
    PG_HBA="/etc/postgresql/16/main/pg_hba.conf"
    sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" $PG_CONF
    sudo sed -i "s/listen_addresses = 'localhost'/listen_addresses = '*'/" $PG_CONF
    echo "host all all 0.0.0.0/0 md5" | sudo tee -a $PG_HBA
    sudo ufw allow 5432/tcp
    sudo systemctl restart postgresql
    sudo -u postgres psql -c "CREATE DATABASE order_platform;"
    sudo -u postgres psql -c "CREATE USER bonun WITH PASSWORD 'password';"
    sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE order_platform TO bonun;"
    sudo -u postgres psql -d order_platform <<EOF
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE TABLE p_user (created_at TIMESTAMP(6) NOT NULL, created_by BIGINT, deleted_at TIMESTAMP(6), deleted_by BIGINT, updated_at TIMESTAMP(6) NOT NULL, updated_by BIGINT, user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, phone_number VARCHAR(20) NOT NULL UNIQUE, user_role VARCHAR(20) NOT NULL CHECK (user_role IN ('CUSTOMER','OWNER','MANAGER','MASTER')), nickname VARCHAR(50) NOT NULL UNIQUE, real_name VARCHAR(50) NOT NULL, username VARCHAR(50) NOT NULL UNIQUE, email VARCHAR(100) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL);
    CREATE TABLE p_category (created_at TIMESTAMP(6) NOT NULL, created_by BIGINT, deleted_at TIMESTAMP(6), deleted_by BIGINT, updated_at TIMESTAMP(6) NOT NULL, updated_by BIGINT, category_id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), category_name VARCHAR(100) NOT NULL);
    CREATE TABLE p_region (is_active BOOLEAN NOT NULL, created_at TIMESTAMP(6) NOT NULL, created_by BIGINT, deleted_at TIMESTAMP(6), deleted_by BIGINT, updated_at TIMESTAMP(6) NOT NULL, updated_by BIGINT, region_id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), sido VARCHAR(20), eupmyendong VARCHAR(30), sigungu VARCHAR(30), region_name VARCHAR(100) NOT NULL, full_name VARCHAR(255) NOT NULL, region_code VARCHAR(255) NOT NULL UNIQUE);
    CREATE TABLE p_store (created_at TIMESTAMP(6) NOT NULL, created_by BIGINT, deleted_at TIMESTAMP(6), deleted_by BIGINT, min_order_amount BIGINT NOT NULL, updated_at TIMESTAMP(6) NOT NULL, updated_by BIGINT, user_id BIGINT NOT NULL REFERENCES p_user(user_id), category_id UUID NOT NULL REFERENCES p_category(category_id), region_id UUID NOT NULL REFERENCES p_region(region_id), store_id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), phone_number VARCHAR(20), store_name VARCHAR(100) NOT NULL, address VARCHAR(255) NOT NULL, description VARCHAR(255), store_accept_status VARCHAR(255) NOT NULL CHECK (store_accept_status IN ('PENDING','APPROVE','REJECT')));
    CREATE TABLE p_cart (created_at TIMESTAMP(6) NOT NULL, created_by BIGINT, deleted_at TIMESTAMP(6), deleted_by BIGINT, updated_at TIMESTAMP(6) NOT NULL, updated_by BIGINT, user_id BIGINT NOT NULL UNIQUE REFERENCES p_user(user_id), cart_id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4());
    CREATE TABLE p_user_address (is_default BOOLEAN NOT NULL, created_at TIMESTAMP(6) NOT NULL, created_by BIGINT, deleted_at TIMESTAMP(6), deleted_by BIGINT, updated_at TIMESTAMP(6) NOT NULL, updated_by BIGINT, user_id BIGINT NOT NULL REFERENCES p_user(user_id), address_id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), alias VARCHAR(50) NOT NULL, address VARCHAR(255) NOT NULL, address_detail VARCHAR(255) NOT NULL);
    CREATE TABLE p_refresh_token (created_at TIMESTAMP(6) NOT NULL, created_by BIGINT, deleted_at TIMESTAMP(6), deleted_by BIGINT, expiration BIGINT NOT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, updated_at TIMESTAMP(6) NOT NULL, updated_by BIGINT, user_id BIGINT NOT NULL UNIQUE REFERENCES p_user(user_id), token TEXT NOT NULL);
    CREATE TABLE p_menu (is_hidden BOOLEAN NOT NULL, created_at TIMESTAMP(6) NOT NULL, created_by BIGINT, deleted_at TIMESTAMP(6), deleted_by BIGINT, price BIGINT NOT NULL, updated_at TIMESTAMP(6) NOT NULL, updated_by BIGINT, category_id UUID NOT NULL REFERENCES p_category(category_id), menu_id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), store_id UUID NOT NULL REFERENCES p_store(store_id), name VARCHAR(100) NOT NULL, description VARCHAR(255));
    CREATE TABLE p_orders (is_refundable BOOLEAN NOT NULL, created_at TIMESTAMP(6) NOT NULL, created_by BIGINT, deleted_at TIMESTAMP(6), deleted_by BIGINT, total_price BIGINT NOT NULL, updated_at TIMESTAMP(6) NOT NULL, updated_by BIGINT, user_id BIGINT REFERENCES p_user(user_id), orders_id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), store_id UUID NOT NULL REFERENCES p_store(store_id), order_channel VARCHAR(20) NOT NULL CHECK (order_channel IN ('OFFLINE','ONLINE')), order_status VARCHAR(20) NOT NULL CHECK (order_status IN ('PENDING','ACCEPTED','COOKING','IN_DELIVERY','COMPLETED','REJECTED','REFUNDED','FAILED')), receipt_method VARCHAR(20) NOT NULL CHECK (receipt_method IN ('DELIVERY','TAKE_OUT','TAKE_IN')), payment_method VARCHAR(50) NOT NULL CHECK (payment_method IN ('CREDIT_CARD','SIMPLE_PAY','BANK_TRANSFER','CASH')), delivery_address VARCHAR(255) NOT NULL, order_history TEXT NOT NULL, request_message VARCHAR(255));
    CREATE TABLE p_b_order_item (quantity INTEGER NOT NULL, created_at TIMESTAMP(6) NOT NULL, created_by BIGINT, deleted_at TIMESTAMP(6), deleted_by BIGINT, price BIGINT NOT NULL, updated_at TIMESTAMP(6) NOT NULL, updated_by BIGINT, order_item_id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), orders_id UUID NOT NULL REFERENCES p_orders(orders_id), menu_name VARCHAR(100) NOT NULL);
    CREATE TABLE p_review (created_at TIMESTAMP(6) NOT NULL, created_by BIGINT, deleted_at TIMESTAMP(6), deleted_by BIGINT, rating BIGINT NOT NULL, updated_at TIMESTAMP(6) NOT NULL, updated_by BIGINT, user_id BIGINT NOT NULL REFERENCES p_user(user_id), b_order_id UUID NOT NULL UNIQUE REFERENCES p_orders(orders_id), review_id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), store_id UUID NOT NULL REFERENCES p_store(store_id), content VARCHAR(255) NOT NULL, store_name VARCHAR(255), user_name VARCHAR(255));
    CREATE TABLE p_payment (payment_method SMALLINT NOT NULL CHECK (payment_method >= 0 AND payment_method <= 3), amount BIGINT NOT NULL, created_at TIMESTAMP(6) NOT NULL, created_by BIGINT, deleted_at TIMESTAMP(6), deleted_by BIGINT, updated_at TIMESTAMP(6) NOT NULL, updated_by BIGINT, orders_id UUID NOT NULL UNIQUE, payment_id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), payment_key VARCHAR(255) NOT NULL, payment_status VARCHAR(255) NOT NULL CHECK (payment_status IN ('COMPLETED','FAILED','CANCELLED')));
    CREATE TABLE p_payment_etc (created_at TIMESTAMP(6) NOT NULL, created_by BIGINT, deleted_at TIMESTAMP(6), deleted_by BIGINT, updated_at TIMESTAMP(6) NOT NULL, updated_by BIGINT, payment_etc_id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), payment_id UUID NOT NULL REFERENCES p_payment(payment_id), payment_response TEXT NOT NULL);
    EOF


  tags = merge(var.tags, {
    Name = "${var.name}-postgres"
  })
}